
version: '3'
services:

  caddx_server:
    build:
      context: "."
    container_name: "caddx_server"
    ports:
      - "5007:5007"
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /appdata/caddx_server:/config
    environment:
      - CONFIG_FILE=${CONFIG_FILE:-/config/config.yaml}
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
      - API_ADDR=${API_ADDR:-0.0.0.0}
      - API_PORT=5007
      - MQTT_BROKER=192.168.9.12
      - MQTT_PORT=1883
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASS=${MQTT_PASS}
      - MQTT_STATE_TOPIC=home/alarm
      - MQTT_COMMAND_TOPIC=home/alarm/set
      - MQTT_TIMEOUT=10
      - SOL_ADDR=""
      - SERIAL_PORT=${SERIAL_PORT}
      - SERIAL_BAUD=38400

    restart: "unless-stopped"

